### ISSUE TITLE
FRP: Pull partner icons from github

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yPartners#158]
### What is your proposal 🚀
Instead of storing partner icons in this repo pull them from https://github.com/yearn/yearn-assets/tree/master/icons/protocols

### What does this solve ? 🛠
Partners can upload their own icons decentralizing the icon creation task

### More 🔎
*N/A*

**Comment by DarkGhost7** [comment]
It should have all partner icons and the monochrome icons as well

**Comment by Itzabelli** [comment]
@DarkGhost7 Changes are all done yes. We were waiting until it was merged into main to close this issue. We got an approving review late Friday and the changes were merged into develop. 

So all that is needed is for someone that is authorized to click approve / merge on this last PR (below) to make it go live on main then we can close the issue

- https://github.com/yearn/yPartners/pull/169
