### ISSUE TITLE
FRP: Make partner dashboard URLs shareable

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yPartners#159]
### What is your proposal 🚀
Make the partner's dashboard URL resolve to their dashboard. Right now something like this

https://partners.yearn.finance/dashboard/abracadabra

Doesn't show Abra's dashboard. It doesn't have to be their name, it can be the treasury address. 

### What does this solve ? 🛠
Makes URLs shareable. Which is desirable.

### More 🔎
*N/A*

**Comment by 0xMirim** [comment]
I've made various attempts to get this working for about 2 days, it's not as easy as it initially appears.

Some of my attempts have gotten very close, I may retrace steps to those solutions tomorrow and see if there is a way forward even if minor UI issues exist. If I can't get a working solution by tomorrow I'll have to set this feature aside for the time being.

**Comment by 0xMirim** [comment]
Good news! Backtracking and iterating on previous partial solutions worked. I have things working as I wanted on my local branch will submit the PR later today or tomorrow.
